defaults:
  - override hydra/sweeper: optuna

## Training h-parameters
data: /path/to/train_data_dir
batch_size: 64
epochs: 100
eary_stop: 10
num_trials: 3

model:
  id:

optimizer:
  learning_rate: 
  betas: 
  weight_decay: 

## hydra settings
hydra:
  sweeper:
    sampler:
      seed: 1234
    direction: maximize
    study_name: no-name
    storage: null
    n_trials: 30
    n_jobs: 1

## mlflow settings
mlflow:
  exp_name: EXP001-2022xxxx
